# Generated by Django 6.0.2 on 2026-02-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='german_word',
        ),
        migrations.RemoveField(
            model_name='card',
            name='russian_translation',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='card',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='cards/pdf/', verbose_name='PDF файл'),
        ),
        migrations.AddField(
            model_name='card',
            name='term',
            field=models.CharField(default='', max_length=255, verbose_name='Термин (DE/EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='translation',
            field=models.CharField(default='', max_length=255, verbose_name='Перевод (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='title',
            field=models.CharField(default='placeholer', max_length=100, verbose_name='Название колоды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.deck'),
        ),
    ]
