# Generated by Django 6.0.2 on 2026-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_german_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='gender',
            field=models.CharField(blank=True, choices=[('masc', 'der (Maskulinum - Мужской)'), ('fem', 'die (Femininum - Женский)'), ('neut', 'das (Neutrum - Средний)'), ('', '--- (Kein Artikel/Andere - Нет артикля)')], default='', max_length=4, verbose_name='Артикл (Genus)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='term',
            field=models.CharField(default='', max_length=255, verbose_name='Термин (DE)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='translation',
            field=models.CharField(default='', max_length=255, verbose_name='Перевод (RU)'),
        ),
    ]
